### ISSUE TITLE
Oops! The embed code for this video is not valid.

### ISSUE THREAD

**Issue by anartfulscience** [viktorbergehall/lazyframe#2]
Hello,

Great plugin. The only issue I'm having is with Vimeo. As soon as I swop out your example I'm getting the error, 

Oops!
The embed code for this video is not valid.
https://vimeo.com/17079380

Can you help?

All the best, Stephen

Also is there anyway of setting the wmode, showinfo & modest branding?

**Comment by viktorbergehall** [comment]
Good find! I didn't realize Vimeo video-id's could be 8 characters. I've updated the plugin and it should work now. 

As for wmode etc. I've fixed so you can send in any parameters in data-src and the appended iframe will get them.

**Comment by anartfulscience** [comment]
Fantastic! Thanks Viktor :)

**Comment by mv-studio** [comment]
@vb Hi Viktor ! We are experiencing something similar with vimeo-id's that have 10 characters now -> vimeo video doesn't work (Oops, video doesn't exist) -> but they are working on Vimeo.
