### ISSUE TITLE
Ajax question

### ISSUE THREAD

**Issue by luyendao** [viktorbergehall/lazyframe#3]
Hi Victor,

Thank you for your code - i'm hoping I can ask you an integration question. I'm making an ajax call into a modal using the Featherlight modal which works fine.

After it's open I use a callback to re-initialize your lazyframe function and bind it to the .lazyframe' class. Everything works except it doesn't pull the thumbnail from the Youtube API, but i can play the video just fine.

The only difference with a stand-along page of the same content I have working with lazy frame, is the background image isn't populated with the image from the youtube API.

I thought i'd field a question if you have any thoughts. Thanks!

**Comment by viktorbergehall** [comment]
Thanks for your input.
It's hard to say without looking at any code. Could you set up a fiddle/codepen that demonstrates the issue? 
If I were to guess I'd probably set the lazyload option to false on initialization
