### ISSUE TITLE
YouTube player parameters

### ISSUE THREAD

**Issue by vlaskiz** [viktorbergehall/lazyframe#5]
Hello,

Any way to set these up (to disable related videos at the end, hide controls etc)? Adding those at the end of data source url does not seem to work.

**Comment by viktorbergehall** [comment]
Thanks for your feedback. Just add the params to the `data-src` and it will work. Please have a look at [this codepen](http://codepen.io/viktor/pen/EgNpav) for reference.

**Comment by vlaskiz** [comment]
I literally made a mistake between the url, which is added dynamically, and parameters. Everything works as expected. Thank you.
