### ISSUE TITLE
How to get thumbnail?

### ISSUE THREAD

**Issue by mumus** [viktorbergehall/lazyframe#7]
Hello. How to get thumbnail to manipulate with image? Is there simple way to wait untill it download, and then to get it without timeout?

lazyframe('.lazyframe', {
        apikey: '',
        onLoad: function (lazyframe) {
            console.log(lazyframe.settings.thumbnail); //undefined
            setTimeout(function(){
                console.log(lazyframe.settings.thumbnail); // good
            }, 1000);
        }
    });

**Comment by viktorbergehall** [comment]
Hello, thanks for your feedback!
Update the plugin (v 1.1.3) and there will be a callback named `onThumbnailLoad` with the image url
